project:
  path: /var/www/html
  mysql:
    DB_ROOT_PASSWORD: root
    DB_NAME: drupal
    DB_USER: root
    DB_PASSWORD: root
composer:
  config:
    timeout: 2000
    verbose: false
  dependencies:
    drupal/coder:
      install: true
      require-dev: true
      post-command: php script.php phpcs-config
    drupal/devel:
      install: false
      require-dev: true
      drush-command: drush en devel
    mglaman/drupal-check:
      install: false
      require-dev: true
      post-command:
    drupal/hacked:
      install: false
      require-dev: true
      drush-command: drush en hacked
    drupal/twig_vardumper:
      install: false
      require-dev: true
      drush-command: drush en twig_vardumper
    drupal/debug_bar:
      install: false
      require-dev: true
      drush-command: drush en debug-bar
# Check extension to installº
    drupal/drupal-extension:
      install: false
      require-dev: true
      post-command: