project:
  install_path: /var/www/html
  project_name: drupal
  # This value is not configurable.
  path: $install_path/$project_name
  mysql:
    DB_ROOT_PASSWORD: root
    DB_NAME: drupal
    DB_USER: root
    DB_PASSWORD: root
behat:
  behat_url: http://php/drupal/web
  selenium_url: http://selenium:4444/wd/hub
  # This value is not configurable.
  drupal_root: $path/web

composer:
  config:
    timeout: 2000
    verbose: false
  dependencies:
    dealerdirect/phpcodesniffer-composer-installer:
      install: true
      require-dev: true
      drush-command:
    drupal/coder:
      install: true
      require-dev: true
      switches:
        - global
      post-command: php run.php phpcs-config
    drupal/devel:
      install: false
      require-dev: true
      drush-command: drush en devel -y
    mglaman/drupal-check:
      install: false
      require-dev: true
      switches:
        - global
      post-command:
    drupal/hacked:
      install: false
      require-dev: true
      drush-command: drush en hacked -y
    drupal/twig_vardumper:
      install: false
      require-dev: true
      drush-command: drush en twig_vardumper -y
    drupal/debug_bar:
      install: false
      require-dev: true
      drush-command: drush en debug-bar -y
    drupal/drupal-extension:
      install: true
      require-dev: true
      post-command: php run.php behat-config